import { CreateServerFormData } from "../types";

export const generateServerProperties = (data: CreateServerFormData): string => {
  // Static template for server.properties
  return `#Minecraft server properties
#Generated by NodeStack
server-port=${data.port}
max-players=${data.maxPlayers}
motd=${data.motd.replace(/\n/g, ' ')}
view-distance=${Math.max(4, Math.min(16, Math.floor(data.memory / 256)))}
online-mode=true
difficulty=normal
gamemode=survival
enable-command-block=false
spawn-protection=16
enable-rcon=false
allow-flight=false
allow-nether=true
white-list=false
pvp=true
snooper-enabled=false
hardcore=false
`;
};

export const getServerJarUrl = (version: string): string => {
  // Static mapping for supported versions to official Mojang downloads
  const versions: Record<string, string> = {
    '1.20.4': 'https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar',
    '1.20.1': 'https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar',
    '1.19.4': 'https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar'
  };

  return versions[version] || '';
};